### PR TITLE
A command argument parser

### PR DESCRIPTION
**Pull request by applejuiceyy**
reading the raw values can get very cumbersome, specially when these arguments may not exist on the message content with the right context and when including arguments with spaces, so I wrote a command argument parser that aims to fix these issues

an example has been written on [the repository](https://github.com/applejuiceyy/LightLoop/blob/main/src/message/example.js) denoting every setting of the parser

I tested it a lot but stuff can still show up so I recommend taking a look at it or something

### CODE REVIEW

**Comment by applejuiceyy** [comment]
Also an asterisk that should be pointed out when converting commands to this

For serious command (like moderation commands) all context options for the relevant parameters should be turned off

This is because they ""desperately"" try to find an argument to provide if that argument wasn't given to them (by searching in the message itself), in order to make the command usage feel very dynamic to the end-user

However one wouldn't want them to desperately try to find a member to ban in a ban command, so it's recommended that they should be turned off

**Comment by applejuiceyy** [comment]
I don't think I have any more ideas to add to this PR

**Comment by GNamimates** [comment]
Public 
Relations

**Comment by Manuel-3** [comment]
While this is a proper command parser solution, I deem it to be a little overkill for what I am looking for in this project. After careful consideration and evaluation of this PR I have concluded that unfortunately I will not be merging these changes.

This is because of the following reasons:
* Most importantly: Maintaining this will be more difficult for me in the future
* The project doesn't need this excessive amount of features for command parsing

I am still thankful for your contribution and I hope you can use this system in another project in the future.

Having said all of this, I am implementing a simpler command parser that just fixes the main problem the project had in the first place: Removing the currently bad argument parsing from the individual commands and moving this responsibility to a central place that handles all that from there. This was inspired by your solution and has some similarities, for example the ability to do different command overloads and argument options.

**Comment by Manuel-3** [comment]
See 93dab6a1dde3322310a7d793506e2fb216f34b88

**Comment by Manuel-3** [comment]
You also seem to have added some more little tweaks that are kind of unrelated like supporting webhooks, I would gladly come back to you / talk to you about those in the near future.

**Comment by applejuiceyy** [comment]
I do understand that it'd be harder to maintain for someone that didn't write any of it
but I don't see how it is overkill, for me this command parser implements the adequate features that a command parser should have
what features are you talking about that make it overkill?

**Comment by Manuel-3** [comment]
Overkill might have been the wrong word... overcomplicated maybe?

For example
* The way parse error highlighting is done, showing where exactly the error occured, like a compiler
* Registering commands/overloads/arguments isn't very intuitive/handy
* The way the registry works isn't as straightforward as it could be, I am sure the way you did it has advantages for your usecase, but I felt like just having different files each with a function to validate a type of input is enough

**Comment by applejuiceyy** [comment]
will it be pondered upon again if I fix these issues?

**Comment by Manuel-3** [comment]
These aren't really "issues" by nature in the first place, so I don't think you should be attempting to fix them. It's just that I prefer a different approach to the problem. My intention is definitely not saying that your code is "bad" at all, it's just not the way I would do it. Every solution has it's pros and cons. Obviously mine isn't perfect, but it's good enough and exactly what I am looking for personally. As I said the main reason is because it would make maintaining this project a lot more difficult and straining for me in the future.

I am truly sorry if I just made you waste a lot of time and effort you spent on making this. That's why I really hope you can use this in a future project of yours, maybe you will make your own discord bot or some kind of bot command template?

**Pull request closed without merging**
